spring:
  application:
    name: sea-battle-bot
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  flyway:
    baseline-on-migrate: true

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  creator-chat-id: ${BOT_CREATOR_CHAT_ID}

logging:
  level:
    root: INFO
    org.urfu.semyonovowa: INFO
    org.telegram: WARN
